[package]
name = "molt"
version = "0.1.0"
edition = "2024"
default-run = "molt"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
proc-macro2 = { version = "1.0.92", features = ["span-locations"] }
quote = "1.0.37"
syn = { version = "2.0.89", features = ["full", "parsing"] }
codespan-reporting = "0.12.0"
walkdir = "2.5.0"
thiserror = "2.0.12"

[features]
debug-print = []
default = ["debug-print"]

[dev-dependencies]
insta = { version = "1.41.1"}

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[[bin]]
name = "molt"
path = "src/main.rs"

[profile.dev]
debug = "line-tables-only"
